[package]
name = "simple_scan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11"}
ipnet = "2.9.0"
num_cpus = "1.16.0"
surge-ping = "0.8.0"
tokio = {version="1.35.0",features = ["rt-multi-thread","net","sync","time"]}

[profile.release]
lto= true
codegen-units = 1
strip = true
opt-level = "z"
panic = 'abort'
